name: flutter_facebook_image_picker
description: Flutter plugin that allows you to display Facebook multi image picker on iOS and Android.
version: 0.0.15
author: Radoslav Vitanov <radoslav.vitanov@icloud.com>
homepage: https://github.com/Sh1d0w/flutter_facebook_image_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/loading.gif
